# add stages here
stages:
  get_data:
    cmd: python src/data/fetch_data.py --config=configs/config.yaml
    deps:
      - src/data/fetch_data.py
      - src/utils/helper.py
      - configs/config.yaml
    outs:
      - data/data.xml

  prepare_data:
    cmd: python src/data/prepare_data.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/data/prepare_data.py
      - src/utils/helper.py
      - data/data.xml
      - configs/config.yaml
    params:
      - prepare.seed
      - prepare.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

  featurize:
    cmd: python src/data/create_features.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/data/create_features.py
      - src/utils/helper.py
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
      - configs/config.yaml
    params:
      - featurize.max_features
      - featurize.ngrams
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl

  train:
    cmd: python src/models/train_fn.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/models/train_fn.py
      - src/utils/helper.py
      - artifacts/features/train.pkl
      - configs/config.yaml
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - artifacts/model/model.pkl

  evaluate:
    cmd: python src/models/test_fn.py --config=configs/config.yaml
    deps:
      - src/models/test_fn.py
      - src/utils/helper.py
      - artifacts/features/test.pkl
      - configs/config.yaml
      - artifacts/model/model.pkl
    metrics:
      - scores.json:
          cache: false
    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: fpr
          y: tpr